### PR TITLE
car servicing feature added

### PR DESCRIPTION
**Pull request by 05042022**
please team review

### CODE REVIEW

**Review by engrk4u — CHANGES_REQUESTED** [review]
Add echo "Input last serviced date and mileage"

**Comment by qbamms** [comment]
Perfect feature update, great job.

**Comment by Captainto** [comment]
Great feature update team.

**Comment by Captainto** [comment]
Great update, Well done team

**Comment by Pasima-kiera** [comment]
Good job,well done team

**Review by contactbilal05 — COMMENTED** [review]
Good job

**Comment by Pasima-kiera** [comment]
Bravo

**Pull request merged**
